- step:
    name: train
    image: tensorflow/tensorflow
    command: python train.py
    environment: aws-p3-xlarge
    runtime-config-preset: preset-abc123

- pipeline:
    name: Training pipeline
    nodes:
      - name: train-node
        type: execution
        step: train
        override:
          # when overriding runtime-config-preset, environment must also be overridden
          environment: aws-p3-2xlarge
          runtime-config-preset: preset-xyz789
    edges: []
